const express=require('express');const http=require('http');const {Server}=require('socket.io');const bcrypt=require('bcryptjs');const {Pool}=require('pg');
const app=express(),server=http.createServer(app),io=new Server(server);const PORT=process.env.PORT||10000;
const DATABASE_URL=process.env.DATABASE_URL; if(!DATABASE_URL) console.warn('DATABASE_URL is not set');
const pool=new Pool({connectionString:DATABASE_URL,ssl:DATABASE_URL?{rejectUnauthorized:false}:false});
app.use(express.json());app.use(express.static('public'));
const MAX_CARDS=15000;let cards=[];const online=new Map();const battles=new Map();
const prices=[30000,45000,60000,80000,100000,130000,160000,200000,250000,300000,350000,420000,500000,600000,700000,800000,900000,1000000,1100000,1200000,1300000,1400000,1500000,1650000,1800000,2000000,2300000,2600000,3000000,3500000];
const packs=prices.map((price,i)=>({id:i+1,name:`카드팩 ${i+1}`,price,count:i<10?7:i<20?8:7,rareBoost:1+i*0.16}));
function imageCandidates(base){if(!base)return [];return [`${base}/high.webp`,`${base}/high.png`,`${base}/low.webp`,`${base}/low.png`,`${base}/high.jpg`];}
async function initDB(){await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,money BIGINT NOT NULL DEFAULT 100000,wins INT NOT NULL DEFAULT 0,created_at TIMESTAMPTZ DEFAULT now());CREATE TABLE IF NOT EXISTS inventory(id BIGSERIAL PRIMARY KEY,user_id INT REFERENCES users(id) ON DELETE CASCADE,card_id TEXT NOT NULL,name TEXT NOT NULL,rarity TEXT,value BIGINT NOT NULL,image_base TEXT,created_at TIMESTAMPTZ DEFAULT now());CREATE INDEX IF NOT EXISTS inventory_user_idx ON inventory(user_id);`)}
async function loadCards(){const out=[];const per=100;for(let page=1;page<=150 && out.length<MAX_CARDS;page++){const u=`https://api.tcgdex.net/v2/en/cards?pagination:page=${page}&pagination:itemsPerPage=${per}`;const r=await fetch(u);if(!r.ok)break;const data=await r.json();if(!Array.isArray(data)||!data.length)break;for(const c of data){if(out.length>=MAX_CARDS)break;out.push({id:c.id,name:c.name,rarity:(c.rarity||'Common').toUpperCase(),imageBase:c.image||null,value:valueForRarity(c.rarity)});}if(data.length<per)break;}cards=out;console.log(`Loaded ${cards.length} TCGdex cards`)}
function valueForRarity(r='Common'){const x=r.toLowerCase();if(x.includes('secret'))return 15000000;if(x.includes('illustration')||x.includes('ultra')||x.includes('special'))return 1500000;if(x.includes('rare'))return 250000;if(x.includes('uncommon'))return 60000;return 30000}
function publicUser(u){return {id:u.id,username:u.username,money:Number(u.money),wins:u.wins}}
async function broadcast(){const {rows}=await pool.query('SELECT id,username,money,wins FROM users ORDER BY money DESC LIMIT 20');io.emit('leaderboard',rows.map(publicUser));io.emit('online',[...online.values()].map(publicUser))}
function randomFrom(pool){return pool[Math.floor(Math.random()*pool.length)]}
function pickLast(pack){const roll=Math.random();const boost=pack.rareBoost;const secret=Math.min(.08,.001*boost),ultra=Math.min(.28,.008*boost),rare=Math.min(.65,.05*boost);let wanted='COMMON';if(roll<secret)wanted='SECRET';else if(roll<secret+ultra)wanted='ULTRA';else if(roll<secret+ultra+rare)wanted='RARE';let p=cards.filter(c=>{const r=c.rarity;return wanted==='COMMON'?/(COMMON|UNCOMMON|NORMAL)/.test(r):wanted==='RARE'?/RARE/.test(r)&&!/(ULTRA|SECRET|ILLUSTRATION|SPECIAL)/.test(r):wanted==='ULTRA'?/(ULTRA|ILLUSTRATION|SPECIAL)/.test(r):/SECRET/.test(r)});if(!p.length)p=cards;return randomFrom(p)}
function pickFront(){let p=cards.filter(c=>/(COMMON|UNCOMMON|NORMAL)/.test(c.rarity));if(!p.length)p=cards;return randomFrom(p)}
function sanitizeCard(c,pos){return {id:c.id,name:c.name,rarity:c.rarity,value:c.value,imageCandidates:imageCandidates(c.imageBase),position:pos}}
app.get('/api/packs',(q,s)=>s.json(packs));app.get('/api/cards/count',(q,s)=>s.json({count:cards.length,max:MAX_CARDS}));
app.post('/api/signup',async(req,res)=>{try{const {username,password}=req.body;if(!username||!password||username.length<2||password.length<6)return res.status(400).json({error:'닉네임 2자 이상, 비밀번호 6자 이상'});const hash=await bcrypt.hash(password,12);const {rows}=await pool.query('INSERT INTO users(username,password_hash) VALUES($1,$2) RETURNING id,username,money,wins',[username.trim(),hash]);res.json(publicUser(rows[0]))}catch(e){res.status(409).json({error:'이미 사용 중인 닉네임입니다.'})}});
app.post('/api/login',async(req,res)=>{const {username,password}=req.body||{};const {rows}=await pool.query('SELECT * FROM users WHERE username=$1',[String(username||'').trim()]);if(!rows[0]||!(await bcrypt.compare(String(password||''),rows[0].password_hash)))return res.status(401).json({error:'로그인 정보가 올바르지 않습니다.'});res.json(publicUser(rows[0]))});
app.get('/api/inventory/:userId',async(req,res)=>{const {rows}=await pool.query('SELECT id,card_id,name,rarity,value,image_base FROM inventory WHERE user_id=$1 ORDER BY created_at DESC',[req.params.userId]);res.json(rows.map(x=>({...x,imageCandidates:imageCandidates(x.image_base)}))) });
io.on('connection',socket=>{socket.on('join',async({userId})=>{const {rows}=await pool.query('SELECT id,username,money,wins FROM users WHERE id=$1',[userId]);if(!rows[0])return;socket.data.userId=rows[0].id;online.set(socket.id,rows[0]);await broadcast()});socket.on('openPack',async({packId})=>{const uid=socket.data.userId,pack=packs.find(x=>x.id===Number(packId));if(!uid||!pack)return;const client=await pool.connect();try{await client.query('BEGIN');const ur=await client.query('SELECT * FROM users WHERE id=$1 FOR UPDATE',[uid]);const u=ur.rows[0];if(Number(u.money)<pack.price){await client.query('ROLLBACK');return socket.emit('errorMsg','잔액이 부족합니다.')}const result=[];for(let i=0;i<pack.count-1;i++)result.push(pickFront());result.push(pickLast(pack));for(const c of result)await client.query('INSERT INTO inventory(user_id,card_id,name,rarity,value,image_base) VALUES($1,$2,$3,$4,$5,$6)',[uid,c.id,c.name,c.rarity,c.value,c.imageBase]);await client.query('UPDATE users SET money=money-$1 WHERE id=$2',[pack.price,uid]);await client.query('COMMIT');const now=(await pool.query('SELECT id,username,money,wins FROM users WHERE id=$1',[uid])).rows[0];socket.emit('packResult',{cards:result.map(sanitizeCard),money:Number(now.money)});online.set(socket.id,now);await broadcast()}catch(e){await client.query('ROLLBACK');socket.emit('errorMsg','팩 처리 중 문제가 발생했습니다.')}finally{client.release()}});
socket.on('sell',async({inventoryId})=>{const uid=socket.data.userId;if(!uid)return;const c=await pool.connect();try{await c.query('BEGIN');const r=await c.query('DELETE FROM inventory WHERE id=$1 AND user_id=$2 RETURNING value',[inventoryId,uid]);if(!r.rows[0]){await c.query('ROLLBACK');return}await c.query('UPDATE users SET money=money+$1 WHERE id=$2',[r.rows[0].value,uid]);await c.query('COMMIT');const u=(await pool.query('SELECT id,username,money,wins FROM users WHERE id=$1',[uid])).rows[0];socket.emit('me',publicUser(u));online.set(socket.id,u);await broadcast()}catch(e){await c.query('ROLLBACK')}finally{c.release()}});
socket.on('battleRequest',async({targetId})=>{const from=online.get(socket.id),target=[...online.entries()].find(([,u])=>u.id===Number(targetId));if(!from||!target)return;const id=`${from.id}-${target[0]}-${Date.now()}`;battles.set(id,{from:from.id,to:target[1].id});io.to(target[0]).emit('battleRequest',{id,from:publicUser(from)})});socket.on('battleAccept',async({id})=>{const b=battles.get(id),uid=socket.data.userId;if(!b||uid!==b.to)return;const winner=Math.random()<.5?b.from:b.to,loser=winner===b.from?b.to:b.from;await pool.query('UPDATE users SET wins=wins+1,money=money+50000 WHERE id=$1',[winner]);await pool.query('UPDATE users SET money=money+10000 WHERE id=$1',[loser]);io.emit('battleResult',{winnerId:winner});battles.delete(id);await broadcast()});socket.on('disconnect',async()=>{online.delete(socket.id);await broadcast()})});
app.get("/", (req, res) => {
  res.sendFile(path.join(__dirname, "public", "index.html"));
});
(async()=>{await initDB();await loadCards();server.listen(PORT,()=>console.log(`Server listening on ${PORT}`))})().catch(e=>{console.error(e);process.exit(1)});
